# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: t2r.proto
# Protobuf Python Version: 4.25.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\tt2r.proto\x12\x1bthird_party.py.tensor2robot\"\xb3\x01\n\x12\x45xtendedTensorSpec\x12\r\n\x05shape\x18\x01 \x03(\x05\x12\r\n\x05\x64type\x18\x02 \x01(\x05\x12\x0c\n\x04name\x18\x03 \x01(\t\x12\x13\n\x0bis_optional\x18\x04 \x01(\x08\x12\x14\n\x0cis_extracted\x18\x05 \x01(\x08\x12\x13\n\x0b\x64\x61ta_format\x18\x06 \x01(\t\x12\x13\n\x0b\x64\x61taset_key\x18\x07 \x01(\t\x12\x1c\n\x14varlen_default_value\x18\x08 \x01(\x02\"\xc4\x01\n\x10TensorSpecStruct\x12N\n\tkey_value\x18\x01 \x03(\x0b\x32;.third_party.py.tensor2robot.TensorSpecStruct.KeyValueEntry\x1a`\n\rKeyValueEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12>\n\x05value\x18\x02 \x01(\x0b\x32/.third_party.py.tensor2robot.ExtendedTensorSpec:\x02\x38\x01\"\xa8\x01\n\tT2RAssets\x12\x43\n\x0c\x66\x65\x61ture_spec\x18\x01 \x01(\x0b\x32-.third_party.py.tensor2robot.TensorSpecStruct\x12\x41\n\nlabel_spec\x18\x02 \x01(\x0b\x32-.third_party.py.tensor2robot.TensorSpecStruct\x12\x13\n\x0bglobal_step\x18\x03 \x01(\x05')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 't2r_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_TENSORSPECSTRUCT_KEYVALUEENTRY']._options = None
  _globals['_TENSORSPECSTRUCT_KEYVALUEENTRY']._serialized_options = b'8\001'
  _globals['_EXTENDEDTENSORSPEC']._serialized_start=43
  _globals['_EXTENDEDTENSORSPEC']._serialized_end=222
  _globals['_TENSORSPECSTRUCT']._serialized_start=225
  _globals['_TENSORSPECSTRUCT']._serialized_end=421
  _globals['_TENSORSPECSTRUCT_KEYVALUEENTRY']._serialized_start=325
  _globals['_TENSORSPECSTRUCT_KEYVALUEENTRY']._serialized_end=421
  _globals['_T2RASSETS']._serialized_start=424
  _globals['_T2RASSETS']._serialized_end=592
# @@protoc_insertion_point(module_scope)
